api/urls.py
from django.urls import path
# from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'api'
urlpatterns = [
    path('forms/', views.ListCreateForm.as_view(), name="forms"),
    path(
        'forms/<int:pk>',
        views.RetrieveUpdateDestroyForm.as_view(),
        name="form"
    ),

    path('inbox/', views.ListCreateInput.as_view(), name="inbox"),
    path(
        'inbox/<int:pk>',
        views.RetrieveUpdateDestroyInput.as_view(),
        name="input"
    ),
    path('inbox/<int:pk>/add_comment', views.add_comment, name='add_comment'),

    path('users/', views.ListCreateUser.as_view(), name="users"),
    path('groups/', views.ListCreateGroup.as_view(), name="groups"),

    path('routes/', views.ListCreateRoute.as_view(), name="routes"),
    path(
        'destinations/',
        views.ListCreateDestination.as_view(),
        name="destinations"
    ),
    path(
        'destinations/<int:pk>',
        views.RetrieveUpdateDestroyDestination.as_view(),
        name="destination"
    ),
]

formation/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import IndexView


urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('forms/', include('forms.urls', namespace='forms')),
    path('inbox/', include('inputs.urls', namespace='inbox')),
    path('routes/', include('routes.urls', namespace='routes')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

routes/urls.py
from django.urls import path
from . import views


app_name = 'routes'
urlpatterns = [
    path('', views.RouteListView.as_view(), name='list'),
    path('create', views.RouteCreateView.as_view(), name='create'),
    path('<int:pk>', views.RouteDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.RouteUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.RouteDeleteView.as_view(), name='delete'),
]

routes/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import models
from django.urls import reverse
from forms.models import Form


User = get_user_model()


class Route(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    form = models.ForeignKey(Form, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return "Route for form: {} created: {}".format(
            self.form.name,
            self.created_at
        )

    def get_absolute_url(self):
        return reverse('forms:detail', kwargs={'pk': self.pk})


class Destination(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(
        max_length=255,
        default=None,
        blank=True,
        null=True
    )
    route = models.ForeignKey(
        Route,
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True
    )
    step = models.IntegerField(default=1)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True
    )
    is_removeable = models.BooleanField(default=True)

    class Meta:
        ordering = ['step']

    def __str__(self):
        return "self.id: {}, route.id: {}, step: {}, user: {}, group: {}, created_at: {}".format(
            self.id,
            self.route,
            self.step,
            self.user,
            self.group,
            self.created_at
        )

routes/admin.py
from django.contrib import admin

# Register your models here.

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

routes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Route
from forms.models import Form


User = get_user_model()


class RouteListView(LoginRequiredMixin, ListView):
    context_object_name = 'routes'
    model = Route
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forms'] = Form.objects.all()
        return context


class RouteDetailView(LoginRequiredMixin, DetailView):
    model = Route


class RouteCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    fields = ['form', 'user', 'group']
    model = Route
    success_url = reverse_lazy('routes:list')
    success_message = "Route created."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        context['groups'] = Group.objects.all()
        return context


class RouteUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    fields = ['form', 'user', 'group']
    model = Route
    success_message = "Route updated."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        context['groups'] = Group.objects.all()
        print('RouteUpdateView context:', context)
        return context


class RouteDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Route
    success_url = reverse_lazy('routes:list')
    success_message = "Route deleted."

routes/templates/routes/route_confirm_delete.html
{% extends 'layout.html' %}

{% block body %}

  <h1>Really Delete?</h1>
  <br />
  
  <form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input class="button alert" type="submit" value="Confirm Delete"/>
    <a class="button large secondary" href="{% url 'routes:update' pk=route.pk %}">Cancel</a>
  </form>
  
{% endblock %}

routes/templates/routes/route_form.html
{% extends 'layout.html' %}

{% block title %}{% if object %}Edit Route{% else %}New Route{% endif %}{% endblock %}

{% block body %}
  
  <h1>{% if not object.pk %}Create Route{% else %}Edit Route{% endif %}</h1>
  {% if object.pk %}<small>Created: {{object.created_at|date:"m/d/Y f"}}</small>{% endif %}
  <br /><br/>

  <form method="post" id="route-form" @submit="submitRouteForm">

    <div class="row">
      <div class="columns large-12">
	  {{ route.as_p }}
	  {% csrf_token %}

	  <div class="grid-container">

	    <destination v-for="dest in dests"
			 :key="dest.name"
			 :id="dest.id"
			 :name="dest.name"
			 :step="dest.step"
			 :destuser="dest.user"
			 :destgroup="dest.group"
			 :users="dest.users"
			 :groups="dest.groups"
			 :is-removeable="dest.isRemoveable"
	                 @remove-dest="removeDest"
	                 @add-destId="addDestId"></destination>


	    <div id="archiveDest" class="card route-dest-card">
	      <div class="card-divider">
		Archive
	      </div>
	      <div class="card-section">
		The Final Countdown... err Destination
	      </div>
	    </div>
	  </div>
      </div>
    </div>

    <br/><hr/>

    <div class="row">
      <div class="columns large-4">
	<button class="button small" type="button" @click="addDest">Add Destination</button>
      </div>

      <div class="columns large-4">
	<input class="button small success" type="submit" value="Save" @click="createRoute" />
	{% if object.pk %}
	  <a href="{% url 'routes:list' %}" class="button secondary small">Cancel</a>
	  <a href="{% url 'routes:delete' pk=object.pk %}" class="button tiny alert float-right">Delete</a>
	{% endif %}
      </div>
    </div>
  </form>

  <script>

   {% if route.instance.pk %}
     var routeId = {{route.instance.pk}};
   {% endif %}
  </script>

{% endblock %}

{% block vue %}
  {% include 'route_vue.html' %}
{% endblock %}

routes/templates/routes/route_list.html
{% extends 'layout.html' %}

{% block title %}Routes{% endblock %}

{% block body %}

  <h1>Route List</h1>

  <h2>Forms</h2>

  <ul class="accordion" data-accordion>
    {% for form in forms %}
      <li class="accordion-item" data-accordion-item>
	<a href="#" class="accordion-title">{{form.name}}</a>

	<div class="accordion-content" data-tab-content>
	  <ul>
	    {% for route in form.route_set.all %}
	      <li><a href="{% url 'routes:update' pk=route.pk %}?form={{form.id}}">
		Starts with:
		{% if route.destination_set.first.user %}
		  <span class="badge">{{route.destination_set.first.user.username}}</span>
		{% else %}
		  <span class="badge">{{route.destination_set.first.group.name}}</span>
		{% endif %}
		&nbsp;&nbsp; Created: 
		<span class="badge">{{route.created_at|date:"m/d/Y f"}}</span>
	      </a></li>
	     {% endfor %}
	  </ul>

	  <a href="{% url 'routes:create' %}?form={{form.id}}" class="button small">Add Route</a>
	</div>
      </li>
    {% endfor %}
  </ul>

{% endblock %}