api/urls.py
from django.urls import path
# from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'api'
urlpatterns = [
    path('forms/', views.ListCreateForm.as_view(), name="forms"),
    path(
        'forms/<int:pk>',
        views.RetrieveUpdateDestroyForm.as_view(),
        name="form"
    ),

    path('inbox/', views.ListCreateInput.as_view(), name="inbox"),
    path(
        'inbox/<int:pk>',
        views.RetrieveUpdateDestroyInput.as_view(),
        name="input"
    ),
    path('inbox/<int:pk>/add_comment', views.add_comment, name='add_comment'),

    path('users/', views.ListCreateUser.as_view(), name="users"),
    path('groups/', views.ListCreateGroup.as_view(), name="groups"),

    path('routes/', views.ListCreateRoute.as_view(), name="routes"),
    path(
        'destinations/',
        views.ListCreateDestination.as_view(),
        name="destinations"
    ),
    path(
        'destinations/<int:pk>',
        views.RetrieveUpdateDestroyDestination.as_view(),
        name="destination"
    ),
]

formation/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import IndexView


urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('forms/', include('forms.urls', namespace='forms')),
    path('inbox/', include('inputs.urls', namespace='inbox')),
    path('routes/', include('routes.urls', namespace='routes')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inputs/urls.py
from django.urls import path
from . import views


app_name = 'inbox'
urlpatterns = [
    path('', views.InputListView.as_view(), name='list'),
    path('create', views.InputCreateView.as_view(), name='create'),
    path('<int:pk>', views.InputDetailView.as_view(), name='detail'),
    path('<int:pk>/delete', views.InputDeleteView.as_view(), name='delete'),
    path('archive/', views.ArchiveListView.as_view(), name='archive'),
    path('approvals/', views.ApprovalListView.as_view(), name='approvals'),
    path('<int:pk>/add_attachment', views.add_attachment, name='add_attachment'),
]

inputs/models.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils import timezone
from forms.models import Form
from routes.models import Route, Destination
import logging


User = get_user_model()
logger = logging.getLogger(__name__)


class Input(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    status = models.CharField(max_length=255, default="new")
    data = JSONField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    form = models.ForeignKey(Form, on_delete=models.CASCADE, default=None)

    route = models.ForeignKey(
        Route,
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True
    )
    route_date = models.DateTimeField(blank=True, null=True)
    route_holder = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        blank=True,
        related_name='user_holding_input'
    )
    route_sender = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        blank=True,
        related_name='user_sent_input'
    )
    current_dest = models.ForeignKey(
        Destination,
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True
    )
    step = models.IntegerField(
        default=0,
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.user.username + ": " + self.status

    def save(self, *args, **kwargs):
        logger.warning('{} | Input: "{}" updated/created by: {}'.format(
            timezone.now(),
            self.form.name,
            self.user.username
        ))
        super(Input, self).save(*args, **kwargs)


class Approval(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    input = models.ForeignKey(Input, on_delete=models.CASCADE, default=None)

    class Meta:
        ordering = ['-created_at']


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    input = models.ForeignKey(Input, on_delete=models.CASCADE, default=None)
    text = models.CharField(max_length=2048)

    class Meta:
        ordering = ['-created_at']


class Attachment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    input = models.ForeignKey(Input, on_delete=models.CASCADE, default=None)
    upload = models.FileField(blank=True, null=True, upload_to='%Y/%m/')

    class Meta:
        ordering = ['created_at']

inputs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from itertools import chain
from operator import attrgetter
from .models import Input, Approval, Attachment
from .mixins import InputHolderMixin

User = get_user_model()


class InputListView(LoginRequiredMixin, ListView):
    context_object_name = 'inputs'
    model = Input
    # paginate_by = 10 # Might look into a better way to do this later...
    table_pagination = False

    def get_queryset(self, *args, **kwargs):
        if ('search' in self.request.GET):
            # Use a raw query to process the search in order to use the
            # PostgreSQL jsonb_each_text function for searching Input.data values.
            qs = Input.objects.raw('''
               select count(*) as num_rows, * from inputs_input 
               join jsonb_each_text(inputs_input.data) e on true 
               join auth_user on (inputs_input.user_id = auth_user.id)
               where e.value like %s and
                     (inputs_input.user_id = %s or
                     inputs_input.route_holder_id = %s)
               group by e.key, inputs_input.id, e.value, auth_user.id;
            ''', ['%' + self.request.GET['search'] + '%',
                  self.request.user.id, self.request.user.id])

            # Add the row count.
            qs.num_rows = sum(1 for q in qs)
        else:
            qs = super(InputListView, self).get_queryset(*args, **kwargs).filter(
                Q(user=self.request.user) | Q(route_holder=self.request.user)
            ).exclude(status='archived')
        return qs
    

class InputCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    fields = ['data', 'form']
    model = Input
    success_url = reverse_lazy('inbox')


class InputDetailView(LoginRequiredMixin, InputHolderMixin, DetailView):
    model = Input

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add a next_user attribute to the Input.data in order to send
        # the Input to the next user, also add a blank comment attribute.
        context['input'].data['next_user'] = ''
        context['input'].data['comment'] = ''
        context['input'].data['attachment'] = ''
        # context['input'].data['dyns'] = ''

        # Used for deciding which user to send the Input to.
        context['users'] = User.objects.all()
        return context


class InputUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    fields = ['data']
    model = Input
    success_message = "Update successful."


class InputDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Input
    success_url = reverse_lazy('inbox:list')
    success_message = "Deletion complete."


class ArchiveListView(LoginRequiredMixin, ListView):
    context_object_name = 'inputs'
    model = Input
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        qs = super(ArchiveListView, self).get_queryset(*args, **kwargs).filter(
            Q(user=self.request.user), Q(status='archived')
        )
        return qs

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approvals'] = Approval.objects.filter(
            user=self.request.user
        ).order_by(
            'input_id',
            '-created_at').distinct('input_id')
        return context


class ApprovalListView(LoginRequiredMixin, ListView):
    context_object_name = 'approvals'
    model = Approval
    paginate_by = 6

    def get_queryset(self, *args, **kwargs):
        qs = super(ApprovalListView, self).get_queryset(*args, **kwargs).filter(
            user=self.request.user
        )
        return qs
    

@login_required()
def add_attachment(request, pk):
    if request.method == 'POST':
        print('request.POST:', request.POST)
        input = Input.objects.get(pk=pk)
        user = User.objects.get(pk=request.POST['user_id'])
        attachment = Attachment.objects.create(input=input, upload=request.FILES['file'], user=user)
        return HttpResponseRedirect(reverse('inbox:detail', args=[pk]))
    else: 
        return HttpResponseRedirect(reverse('inbox:detail', args=[pk]))

inputs/templates/inputs/approval_list.html
{% extends 'layout.html' %}

{% block title %}{% if request.path == '/inbox/archive' %}Archive{% else %}Inbox{% endif %}{% endblock %}

{% block body %}

  <h1>Approvals</h1>


  <div class="row">
    {% for approval in approvals %}
      <div class="columns large-4 small-12">
	<div class="card" style="width: 300px;">
	  <div class="card-divider">
	    <h4><a href="{% url 'inbox:detail' pk=approval.input.pk %}">{{approval.input.form.name}}</a></h4>
	  </div>

	  <div class="card-section">
	    {% if approval.input.form.image %}
	      <a href="{% url 'inbox:detail' pk=approval.input.pk %}">
		<img src="{{approval.input.form.image.url}}" alt="{{approval.input.form.name}}" class="form-image" />
	      </a>
	      <br/><br/>
	      <small><strong>Created at:</strong> {{approval.input.created_at|date:"m/d/Y f"}}</small>
	      <br/>
	      <small><strong>Approved at:</strong> {{approval.created_at|date:"m/d/Y f"}}</small>
	    {% endif %}
	  </div>
	</div>
      </div>
    {% endfor %}
  </div>

  <ul class="pagination text-center" role="navigation" aria-label="Pagination">
    {% if page_obj.has_previous %}
      <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Previous <span class="show-for-sr">page</span></a></li>
    {% endif %}

    <li><a href="#" aria-label="Page {{page_obj.number}}">{{page_obj.number}}</a></li>

    {% if page_obj.has_next %}
      <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
    {% endif %}
  </ul>

  <br/>
  {% if not approvals %}
    <p>No Approvals at this time.</p>
  {% endif %}

{% endblock %}

inputs/templates/inputs/archive_list.html
<h1>Archive</h1>


    <div class="row">
      {% for input in inputs %}
	<div class="columns large-4 small-12">
	  <div class="card" style="width: 300px;">
	    <div class="card-divider">
	      <h4><a href="{% url 'inbox:detail' pk=input.pk %}">{{input.form.name}}</a></h4>
	    </div>

	    <div class="card-section">
	      {% if input.form.image %}
		<a href="{% url 'inbox:detail' pk=input.pk %}">
		  <img src="{{input.form.image.url}}" alt="{{input.form.name}}" class="form-image" />
		</a>
		<br/><br/>
		<small><strong>Created at:</strong> {{input.created_at|date:"m/d/Y f"}}</small>
	      {% endif %}
	    </div>
	  </div>
	</div>
      {% endfor %}
    </div>

    <ul class="pagination text-center" role="navigation" aria-label="Pagination">
      {% if page_obj.has_previous %}
	<li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Previous <span class="show-for-sr">page</span></a></li>
      {% endif %}

      <li><a href="#" aria-label="Page {{page_obj.number}}">{{page_obj.number}}</a></li>

      {% if page_obj.has_next %}
	<li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
      {% endif %}
    </ul>
  </div>
  
  <br/><br/>

inputs/templates/inputs/input_confirm_delete.html
{% extends 'layout.html' %}

{% block body %}

  <h1>Really Delete?</h1>
  <br />
  
  <form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input class="button alert" type="submit" value="Confirm Delete"/>
    <a class="button large secondary" href="{% url 'inbox:detail' pk=input.pk %}">Cancel</a>
  </form>
  
{% endblock %}

inputs/templates/inputs/input_detail.html
{% extends 'layout.html' %}

{% block title %}Inbox {{input.form.name}}{% endblock %}

{% block body %}
  <div id="vue-app">
    
    <div class="row">
      <div class="columns large-12 small-12 form-content">
	  
	  <form method="post" action="{% url 'inbox:create' %}" id="input-form" name="{{input.form.id}}">
	    <div class="form-inner">
	      <div class="row">
		<div class="column small-12 large-10">
		  <h1>{{input.form.name}}</h1>
		  <small>Created: {{input.created_at|date:"m/d/Y g:i:s"}} by: {{input.user.username}}</small>
		  <br/><hr/>
		</div>
	      </div>
	      
	      {% autoescape off %}
		{{input.form.content}}
	      {% endautoescape %}
	    </div>
	  </form>

      </div>
    </div>

    <div class="row">
      <div class="columns large-12 form-buttons">
	{% if input.status != 'archived' %}
	  <br/>
	  <button type="button" class="button success" @click="submitForm">Update</button>
	  <a href="{% url 'inbox:delete' pk=input.pk %}" class="button tiny alert float-right">Delete</a>
	{% endif %}

	<br/><hr/>
      </div>
    </div>

    <div class="row">
      <div class="columns large-8 form-comments">
	<h4>Comments</h4>

	<table>
	  <thead>
	    <tr>
	      <th>Username</th>
	      <th>Comment</th>
	      <th>Date</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for comment in input.comment_set.all %}
	      <tr>
		<td>{{comment.user.username}}</td>
		<td>{{comment.text}}</td>
		<td>{{comment.created_at|date:"m/d/Y g:i:s"}}</td>
	      </tr>
	    {% endfor %}
	  </tbody>
	</table>
	
	{% if input.status != 'archived' %}
	  <textarea id="comment" name="comment" v-model="comment" placeholder="New comment..."></textarea>
	  <button type="button" class="button small" @click="createComment">Save Comment</button>
	{% endif %}
      </div>

      <div class="columns large-4 form-attachments">
	<h4>Attachments</h4>

	<ul>
	  {% for attachment in input.attachment_set.all %}
	    <li><a target="_blank" href="{{attachment.upload.url}}">{{attachment.upload.name}}</a></li>
	  {% endfor %}
	</ul>
	
	{% if input.status != 'archived' %}
	  <form action="{% url 'inbox:add_attachment' pk=input.pk %}" method="post" enctype="multipart/form-data">
	    <input id="attachment-file" name="file" id="file" type="file" />
	    {% csrf_token %}
	    <input type="hidden" name="user_id" value="{{user.id}}" />
	    
	    <button type="submit" class="button small">Add Attachment</button>
	  </form>
	{% endif %}
      </div>
    </div>

    <div class="row">
      <div class="columns large-12 form-routing">
	{% if user == input.route_holder or input.status == 'new' %}
	  <br/><hr/>

	  <h4>Routing</h4>

	  <div class="row">
	    <div class="columns large-4">
	      <autocomplete
		@item-chosen="setUser"
		@blur="setUser"
		title="Send Form"
		:items="users"
		label="username"
		class="inline"></autocomplete>

	      <div id="route-error" class="callout alert hide" data-closable>
		<p>Can't send form to <em id="send-to-user-error"></em></p>
	      </div>
	    </div>

	    <div class="columns large-4">
	      <button type="button" class="button small" title="Send" @click="routeForm">&#x27A4; Send</button>
	      <button type="button" class="button small success float-right" title="Archive" @click="archiveForm">&#9745; Archive</button>
	    </div>
	  </div>
	{% endif %}
      </div>
    </div>

    <div class="row">
      <div class="columns large-12 form-approvals">
	<br/><hr/>
	
	{% if input.status == 'routed' or input.status == 'archived' %}
	  <h4>Appovals</h4>

	  <strong>Current Holder: </strong> {{input.route_holder.username}}
	  <br/><br/>
	  
	  <table>
	    <thead>
	      <tr>
		<th>Username</th>
		<th>Approval Date</th>
	      </tr>
	    </thead>
	    <tbody>
	      {% for approval in input.approval_set.all %}
		<tr>
		  <td>{{approval.user.username}}</td>
		  <td>{{approval.created_at|date:"m/d/Y g:i:s"}}</td>
		</tr>
	      {% endfor %}
	    </tbody>
	  </table>
	{% endif %}
      </div>
    </div>
  </div>
  <br/><br/>

{% endblock %}

{% block vue %}
  {% include 'form_vue.html' with data=input.data %}
{% endblock %}

inputs/templates/inputs/input_form.html
{% extends 'layout.html' %}

{% block body %}

  
{% endblock %}

inputs/templates/inputs/input_list.html
{% extends 'layout.html' %}

{% block title %}{% if request.path == '/inbox/archive' %}Archive{% else %}Inbox{% endif %}{% endblock %}

{% block body %}

  {% if request.path == '/inbox/archive' %}
    {% include 'inputs/archive_list.html' with data=input.data %}
  {% else %}
    <h1>Inbox</h1>

    
    {%  if 'search' in request.GET %}
      <p>
	{% if not inputs.num_rows %}
	  No matches found for <em>{{request.GET.search}}</em>.
	{% else %}
	  {{inputs.num_rows}} matches found for <em>{{request.GET.search}}</em>.
	  {% endif %}
      </p>
    {% endif %}
    
    <div class="row">
      {% for input in inputs %}
	<div class="columns large-4 small-12">
	  <div class="card" style="width: 300px;">
	    <div class="card-divider">
	      <h4><a href="{% url 'inbox:detail' pk=input.pk %}">{{input.form.name}}</a></h4>
	    </div>

	    <div class="card-section">
	      {% if input.form.image %}
		<a href="{% url 'inbox:detail' pk=input.pk %}">
		  <img src="{{input.form.image.url}}" alt="{{input.form.name}}" class="form-image" />
		</a>
		<br/><br/>
		<small><strong>Created at:</strong> {{input.created_at|date:"m/d/Y f"}}</small>
		<br/>
		<small>
		  <strong>Route Holder:</strong>
		  {% if input.route_holder %}{{input.route_holder.username}}{% else %}Me{% endif %}
		</small>
	      {% endif %}
	    </div>
	  </div>
	</div>
      {% endfor %}
    </div>
  {% endif %}


  {% if not inputs %}
    <p>Nothing in the Inbox at this time.</p>
  {% endif %}

{% endblock %}