api/urls.py
from django.urls import path
# from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'api'
urlpatterns = [
    path('forms/', views.ListCreateForm.as_view(), name="forms"),
    path(
        'forms/<int:pk>',
        views.RetrieveUpdateDestroyForm.as_view(),
        name="form"
    ),

    path('inbox/', views.ListCreateInput.as_view(), name="inbox"),
    path(
        'inbox/<int:pk>',
        views.RetrieveUpdateDestroyInput.as_view(),
        name="input"
    ),
    path('inbox/<int:pk>/add_comment', views.add_comment, name='add_comment'),

    path('users/', views.ListCreateUser.as_view(), name="users"),
    path('groups/', views.ListCreateGroup.as_view(), name="groups"),

    path('routes/', views.ListCreateRoute.as_view(), name="routes"),
    path(
        'destinations/',
        views.ListCreateDestination.as_view(),
        name="destinations"
    ),
    path(
        'destinations/<int:pk>',
        views.RetrieveUpdateDestroyDestination.as_view(),
        name="destination"
    ),
]

formation/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import IndexView


urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('forms/', include('forms.urls', namespace='forms')),
    path('inbox/', include('inputs.urls', namespace='inbox')),
    path('routes/', include('routes.urls', namespace='routes')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forms/urls.py
from django.urls import path
from . import views


app_name = 'forms'
urlpatterns = [
    path('', views.FormListView.as_view(), name='list'),
    path('create', views.FormCreateView.as_view(), name='create'),
    path('<int:pk>', views.FormDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.FormUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.FormDeleteView.as_view(), name='delete'),
]

forms/models.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver
from django.utils import timezone
from rest_framework.authtoken.models import Token
import logging


User = get_user_model()
logger = logging.getLogger(__name__)


class Form(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=255, blank=True, null=True, unique=True)
    path = models.CharField(max_length=255, blank=True, null=True)
    content = models.TextField(max_length=20000, blank=True, null=True)
    fields = JSONField(blank=True, null=True)
    public = models.BooleanField(default=False)
    image = models.ImageField(blank=True, null=True, upload_to='form_images')

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forms:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        from bs4 import BeautifulSoup
        # Make sure inputs, textareas, and selects have bound Vue attributes.
        fields = {}

        if self.content:
            soup = BeautifulSoup(self.content, 'html.parser')

            # Add a v-model and @blur attribute to all inputs, textareas,
            # and selects.
            for input in soup.find_all('input'):
                fields[input['name']] = ""
                if 'v-model' not in input:
                    input['v-model'] = input['name']
                if '@blur' not in input:
                    input['@blur'] = 'saveInput'

            for textarea in soup.find_all('textarea'):
                fields[textarea['name']] = ""
                if 'v-model' not in textarea:
                    textarea['v-model'] = textarea['name']
                if '@blur' not in textarea:
                    textarea['@blur'] = 'saveInput'

            for select in soup.find_all('select'):
                fields[select['name']] = ""
                if 'v-model' not in select:
                    select['v-model'] = select['name']
                if '@blur' not in select:
                    select['@blur'] = 'saveInput'

        self.fields = fields
        self.content = soup.prettify()

        print('args:', args, 'kwargs:', kwargs)
        logger.warning('{} | Form: "{}" updated/created'.format(
            timezone.now(),
            self.name
        ))
        super(Form, self).save(*args, **kwargs)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


def log_logins(sender, user, request, **kwargs):
    logger.warning('{} | User: "{}" logged in'.format(
        timezone.now(),
        user.username
    ))


def log_logouts(sender, user, request, **kwargs):
    logger.warning('{} | User: "{}" logged out'.format(
        timezone.now(),
        user.username
    ))

user_logged_in.connect(log_logins)
user_logged_out.connect(log_logouts)

forms/admin.py
from django.contrib import admin
from .models import Form


admin.site.register(Form)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Form

User = get_user_model()


class FormListView(LoginRequiredMixin, ListView):
    context_object_name = 'forms'
    model = Form
    paginate_by = 10


class FormDetailView(LoginRequiredMixin, DetailView):
    model = Form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'].fields['next_user'] = ''
        context['form'].fields['dyns'] = {}

        # Used for deciding which user to send the Input to.
        context['users'] = User.objects.all()
        return context


class FormCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    fields = ['name', 'content', 'image']
    model = Form
    success_url = reverse_lazy('forms:list')
    success_message = "Form created."


class FormUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    fields = ['name', 'content', 'image']
    model = Form
    success_message = "Form updated."


class FormDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Form
    success_url = reverse_lazy('forms:list')
    success_message = "Form deleted."

forms/templates/forms/form_confirm_delete.html
{% extends 'layout.html' %}

{% block body %}

  <h1>Really Delete {{form.name}}?</h1>
  <br />

  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="button small alert">
    &nbsp;&nbsp;
    <a href="{% url 'forms:detail' pk=form.pk %}" class="button large secondary">Cancel</a>
  </form>  

{% endblock %}

forms/templates/forms/form_detail.html
{% extends 'layout.html' %}

{% block title %}{{form.name}}{% endblock %}
		 
{% block body %}
  <div id="vue-app">

    <div class="row">
      <div class="column large-12 small-12 form-content">
	
	  <div class="form-inner">
	    <div class="row">
	      <div class="column small-12 large-10">
		<h1>{{form.name}}</h1>
	      </div>

	      <div class="large-2 small-12">
		<a href="{% url 'forms:update' pk=form.pk %}" class="button small secondary">Edit Form</a>
	      </div>
	    </div>
	    
	    <form method="post" action="{% url 'inbox:create' %}" id="input-form" name="{{form.id}}">
	      {% autoescape off %}
		{{form.content}}
	      {% endautoescape %}

	    </form>
	  </div>

      </div>
    </div>

    <div class="row">
      <div class="column large-8 form-routing">
	<div class="row">
	  <div class="columns large-4">
	    <br/>
	    <autocomplete
	      @item-chosen="setUser"
	      @blur="setUser"
	      title="Send Form"
	      :items="users"
	      label="username"
	      class="inline"></autocomplete>
	    
	    <div id="route-error" class="callout alert hide" data-closable>
	      <p>Can't send form to <em id="send-to-user-error"></em></p>
	    </div>
	  </div>

	  <div class="columns large-4">
	    <br/>
	    <button type="button" class="button small" title="Send" @click="submitForm">&#x27A4; Send</button>
	  </div>
	</div>
      </div>

      <div class="column large-4 form-buttons">
	<br/>
	<button type="button" class="button success" @click="submitForm">Save</button>
	<a href="{% url 'forms:list' %}" class="button secondary float-right">Cancel</a>
      </div>
    </div>

    
    <div class="row">
      <div class="column large-8 form-comments">
	<hr/>
	<h4>Comment</h4>

	<textarea name="comment" id="comment" placeholder="New comment..."></textarea>
      </div>

      <div class="column large-4 form-attachments">
	<hr/>
	<h4>Attachment</h4>

	<form action="" method="post" enctype="multipart/form-data" id="attachment-form">
	  {% csrf_token %}
	  <input type="hidden" name="user_id" value="{{user.id}}" />
	  <input type="file" name="file" id="attachment-file" />
	</form>
      </div>
    </div>


	</div>
	
      </div>
    </div>
  </div>
  <br/><br/>
{% endblock %}

{% block vue %}
  {% include 'form_vue.html' with data=form.fields %}
{% endblock %}

<br/><br/>

forms/templates/forms/form_form.html
{% extends 'layout.html' %}

{% block body %}
  
  <h1>{% if not form.instance.pk %}Create Form{% else %}Edit {{form.instance.name}}{% endif %}</h1>
  <br />
  
  <div class="row">
    <div class="column small-12 large-12">
      <form method="post" enctype="multipart/form-data">
	{{ form.as_p }}
	{% csrf_token %}


	<input class="button" type="submit" value="Save" />
	{% if form.instance.pk %}
	  <a href="{% url 'forms:detail' pk=form.instance.pk %}" class="button secondary">Cancel</a>
	  <a href="{% url 'forms:delete' pk=form.instance.pk %}" class="button tiny alert float-right">Delete</a>
	{% endif %}
      </form>
    </div>
  </div>

{% endblock %}

forms/templates/forms/form_list.html
{% extends 'layout.html' %}

{% block title %}Forms{% endblock %}

{% block body %}

  <h1>Forms</h1>

  <a href="{% url 'forms:create' %}" class="button small">New Form</a>

  <div class="row">
    {% for form in forms %}
      
      <div class="columns large-4 small-12">
	<div class="card" style="width: 300px;">
	  <div class="card-divider">
	    <h4><a href="{% url 'forms:detail' pk=form.pk %}">{{form.name}}</a></h4>
	  </div>

	  <div class="card-section">
	    {% if form.image %}
	      <a href="{% url 'forms:detail' pk=form.pk %}">
		<img src="{{form.image.url}}" alt="{{form.name}}" class="form-image" />
	      </a>
	    {% endif %}
	  </div>
	</div>
      </div>
      
    {% endfor %}
  </div>
{% endblock %}